[workspace]
resolver = "2"
members = [
    "plugin-canvas",
    "plugin-canvas-slint",
    "xtask",
]

[workspace.dependencies]
cursor-icon = "1.1"
plugin-canvas = { path = "plugin-canvas" }
plugin-canvas-slint = { path = "plugin-canvas-slint" }
raw-window-handle = "0.6"
slint = { version = "1.7.2", default-features = false, features = ["accessibility", "compat-1-2", "std"] }

# Internal slint crate versions need to be pinned
# since they don't maintain semver compatibility
i-slint-core = "1.7.2"
i-slint-renderer-skia = { version = "1.7.2", features = ["x11"] }
