[package]
name = "gain-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
plinth-derive.workspace = true
plinth-plugin.workspace = true
serde = "1.0"
serde_json = "1.0"
